package catalog

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

// TmpReferencePath is where the generated tmp reference lands inside the
// skills that carry it (the framework dispatchers and the shared knowledge
// skill). Like ToolingReferencePath, it is part of the skill contract: the
// shipped SKILL.md files point at it conditionally, and apply generates it
// per install from [tmp] in homonto.toml.
const TmpReferencePath = "references/tmp.md"

// SharedKnowledgeSkill names the cross-framework knowledge skill both
// workflow frameworks install. It is not a dispatcher, but it is consulted by
// every workflow entry point (the coordinator and the h-* commands), so it
// carries the generated tmp reference alongside the dispatchers.
const SharedKnowledgeSkill = "homonto"

// RenderTmp composes the generated tmp reference for a declared [tmp]
// directory. Output is byte-deterministic for a given dir — the materialize
// fingerprint depends on that. dir is the validated, workspace-relative path
// from the config (for example ".tmp").
func RenderTmp(dir string) []byte {
	var b []byte
	appendLine := func(format string, args ...any) {
		b = append(b, fmt.Sprintf(format, args...)...)
	}
	appendLine("<!-- Generated by homonto apply. Do not edit: this file is overwritten\n")
	appendLine("     on the next apply. The directory comes from [tmp] in homonto.toml. -->\n\n")
	appendLine("# Workspace tmp directory\n\n")
	appendLine("`%s` — relative to the repository root, gitignored, already created by\n", dir)
	appendLine("apply. Use it for every transient artifact this workflow produces: draft\n")
	appendLine("bodies, fetched packets, scratch output, anything that must not land in a\n")
	appendLine("commit and must not dirty the worktree gates.\n\n")
	appendLine("## Contract\n\n")
	appendLine("- Create subdirectories freely (`%s/...`); recreate the directory if it\n", dir)
	appendLine("  is missing. It is inside the workspace, so every agent that may edit\n")
	appendLine("  can write here without prompts — including custom agents. Read-only\n")
	appendLine("  workers do not write anywhere by design; they return their results and\n")
	appendLine("  the coordinator files any scratch.\n")
	appendLine("- Scratch only. Nothing durable lives here: workflow records, specs, and\n")
	appendLine("  evidence belong in the change workspace; secrets belong nowhere in tmp.\n")
	appendLine("- homonto never deletes content from this directory — cleanup is a\n")
	appendLine("  human decision (`rm -rf %s/...`), never a side effect of apply.\n", dir)
	appendLine("- Any path another skill or command names for transient files may use\n")
	appendLine("  this directory instead of `mktemp`; a declared, known location beats a\n")
	appendLine("  fresh anonymous one for anything a later step must find again.\n")
	return b
}

// TmpFingerprint digests the tmp feature's resolved state — enabled or not,
// and the rendered bytes for the declared dir — so editing [tmp] (declaring
// it, changing dir, removing it) re-renders the reference even though the
// catalog version and every resource byte stay untouched. Same defect class
// the tooling fingerprint closes.
func TmpFingerprint(enabled bool, dir string) string {
	h := sha256.New()
	if !enabled {
		fmt.Fprintf(h, "tmp\x00disabled")
		return hex.EncodeToString(h.Sum(nil))
	}
	body := RenderTmp(dir)
	fmt.Fprintf(h, "tmp\x00%s\x00%d\x00", dir, len(body))
	h.Write(body)
	return hex.EncodeToString(h.Sum(nil))
}
