package catalog

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
)

// ToolingReferencePath is where the generated tooling reference lands inside a
// materialized dispatcher skill. The shipped SKILL.md points at this path, so
// it is part of the skill contract, not an implementation detail.
const ToolingReferencePath = "references/tooling.md"

// toolingFragment maps a provider name to its catalog fragment. The two "none"
// slots have distinct fragments because an undeclared shell proxy and an
// undeclared code-intelligence provider say different things.
func toolingFragment(slot, provider string) (string, error) {
	switch slot {
	case "shell_proxy":
		switch provider {
		case "rtk":
			return "tooling/rtk.md", nil
		case "none":
			return "tooling/none-shell-proxy.md", nil
		}
	case "code_intel":
		switch provider {
		case "graphify":
			return "tooling/graphify.md", nil
		case "okf":
			return "tooling/okf.md", nil
		case "none":
			return "tooling/none-code-intel.md", nil
		}
	}
	return "", fmt.Errorf("catalog: unknown %s provider %q", slot, provider)
}

// IsDispatcher reports whether a skill is its framework's dispatcher — by
// convention the skill named after the framework itself (see the namespacing
// note in catalog/frameworks/onto/framework.toml). Dispatchers are the only
// skills that run the tooling preflight, so they are the only ones that carry
// the generated tooling reference.
func (c *Catalog) IsDispatcher(skillName string) bool {
	_, ok := c.frameworks[skillName]
	return ok
}

// providersDeclared reports whether at least one slot names a real provider,
// which is what makes the shared warn-once rule worth emitting at all.
func providersDeclared(shellProxy, codeIntel string) bool {
	return shellProxy != "none" || codeIntel != "none"
}

// RenderTooling composes the generated tooling reference for a resolved
// provider pair. Output is byte-deterministic for a given pair — the
// materialize fingerprint depends on that.
//
// Providers are taken as plain strings rather than a config.Tooling because
// internal/config imports this package; taking the typed value would close an
// import cycle.
func (c *Catalog) RenderTooling(shellProxy, codeIntel string) ([]byte, error) {
	shellPath, err := toolingFragment("shell_proxy", shellProxy)
	if err != nil {
		return nil, err
	}
	codePath, err := toolingFragment("code_intel", codeIntel)
	if err != nil {
		return nil, err
	}
	shellBody, err := fs.ReadFile(c.fsys, shellPath)
	if err != nil {
		return nil, fmt.Errorf("catalog: read %s: %w", shellPath, err)
	}
	codeBody, err := fs.ReadFile(c.fsys, codePath)
	if err != nil {
		return nil, fmt.Errorf("catalog: read %s: %w", codePath, err)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- Generated by homonto apply. Do not edit: this file is overwritten\n")
	fmt.Fprintf(&b, "     on the next apply. Providers come from [tooling] in homonto.toml:\n")
	fmt.Fprintf(&b, "     shell_proxy = %s | code_intel = %s -->\n\n", shellProxy, codeIntel)
	b.WriteString("# Tooling preflight\n\n")
	b.WriteString("These checks WARN and proceed; they never halt. A degraded workflow is\n")
	b.WriteString("still a working workflow.\n\n")
	if providersDeclared(shellProxy, codeIntel) {
		b.WriteString("**Warn once per change, not per dispatch**: when the active change's\n")
		b.WriteString("Grounding section already records a provider's absence, skip re-warning\n")
		b.WriteString("about that same tool — the situation is known and recorded; repeating it\n")
		b.WriteString("every dispatch is noise. Record a new absence there the first time it is\n")
		b.WriteString("seen.\n\n")
	}
	fmt.Fprintf(&b, "## Shell proxy — %s\n\n", shellProxy)
	b.Write(shellBody)
	if !bytes.HasSuffix(shellBody, []byte("\n")) {
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "\n## Code intelligence — %s\n\n", codeIntel)
	b.Write(codeBody)
	if !bytes.HasSuffix(codeBody, []byte("\n")) {
		b.WriteString("\n")
	}
	return b.Bytes(), nil
}

// ToolingFingerprint digests the resolved provider pair AND the bytes of the
// two selected fragments, so editing a selected fragment re-renders while
// editing an unselected one causes no churn.
//
// This lives outside ContentFingerprint deliberately: that function digests
// per NAMED resource (skill/command/subagent) and fragments are not a declared
// resource. Without this component, editing [tooling] leaves the catalog
// version and every resource byte untouched, so the materialize gate would
// report up to date and serve a stale reference forever.
func (c *Catalog) ToolingFingerprint(shellProxy, codeIntel string) (string, error) {
	body, err := c.RenderTooling(shellProxy, codeIntel)
	if err != nil {
		return "", err
	}
	h := sha256.New()
	fmt.Fprintf(h, "tooling\x00%s\x00%s\x00%d\x00", shellProxy, codeIntel, len(body))
	h.Write(body)
	return hex.EncodeToString(h.Sum(nil)), nil
}
