package catalog

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	embedded "github.com/noviopenworks/homonto/catalog"
)

func baseCatalog(t *testing.T) *Catalog {
	t.Helper()
	c, err := Load(embedded.FS)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	return c
}

// With no providers declared the reference names none of them and points at
// direct file reading — the documented fallback.
func TestRenderTooling_BothNone(t *testing.T) {
	out, err := baseCatalog(t).RenderTooling("none", "none")
	if err != nil {
		t.Fatalf("RenderTooling: %v", err)
	}
	body := string(out)
	for _, absent := range []string{"rtk", "graphify", "okf"} {
		if strings.Contains(body, absent) {
			t.Errorf("both-none reference must not mention %q:\n%s", absent, body)
		}
	}
	if !strings.Contains(body, "direct file reading") {
		t.Errorf("both-none reference should state the direct-file-reading fallback:\n%s", body)
	}
}

// A declared pair renders both providers and never leaks the undeclared one.
func TestRenderTooling_DeclaredPairExcludesOthers(t *testing.T) {
	out, err := baseCatalog(t).RenderTooling("rtk", "okf")
	if err != nil {
		t.Fatalf("RenderTooling: %v", err)
	}
	body := string(out)
	if !strings.Contains(body, "rtk --version") {
		t.Errorf("rtk fragment missing:\n%s", body)
	}
	if !strings.Contains(body, "okf_lookup.py") {
		t.Errorf("okf fragment missing:\n%s", body)
	}
	if strings.Contains(body, "graphify") {
		t.Errorf("undeclared provider graphify leaked into the reference:\n%s", body)
	}
}

// Every accepted combination renders without error and mentions no provider
// it did not declare.
func TestRenderTooling_AllCombinations(t *testing.T) {
	c := baseCatalog(t)
	others := map[string][]string{
		"rtk":      {},
		"graphify": {"okf"},
		"okf":      {"graphify"},
	}
	for _, shell := range []string{"rtk", "none"} {
		for _, code := range []string{"graphify", "okf", "none"} {
			out, err := c.RenderTooling(shell, code)
			if err != nil {
				t.Fatalf("RenderTooling(%q, %q): %v", shell, code, err)
			}
			body := string(out)
			for _, forbidden := range others[code] {
				if strings.Contains(body, forbidden) {
					t.Errorf("RenderTooling(%q, %q) leaked %q", shell, code, forbidden)
				}
			}
			if shell == "none" && strings.Contains(body, "rtk --version") {
				t.Errorf("RenderTooling(%q, %q) leaked the rtk probe", shell, code)
			}
		}
	}
}

// The header must mark the file generated so a user does not hand-edit it.
func TestRenderTooling_HeaderNamesProvidersAndWarns(t *testing.T) {
	out, err := baseCatalog(t).RenderTooling("rtk", "graphify")
	if err != nil {
		t.Fatalf("RenderTooling: %v", err)
	}
	body := string(out)
	for _, want := range []string{"Generated by", "homonto.toml", "shell_proxy = rtk", "code_intel = graphify"} {
		if !strings.Contains(body, want) {
			t.Errorf("header missing %q:\n%s", want, body)
		}
	}
}

// Rendering must be byte-deterministic or the fingerprint means nothing.
func TestRenderTooling_Deterministic(t *testing.T) {
	c := baseCatalog(t)
	first, err := c.RenderTooling("rtk", "graphify")
	if err != nil {
		t.Fatalf("RenderTooling: %v", err)
	}
	for range 3 {
		again, err := c.RenderTooling("rtk", "graphify")
		if err != nil {
			t.Fatalf("RenderTooling: %v", err)
		}
		if !bytes.Equal(first, again) {
			t.Fatal("RenderTooling is not deterministic across calls")
		}
	}
}

// Materialize writes the generated reference into the dispatcher skill (the
// one named after its framework) and into no other skill.
func TestMaterialize_WritesSidecarForDispatchersOnly(t *testing.T) {
	dst := t.TempDir()
	c := baseCatalog(t)
	if err := c.Materialize(dst, []string{"onto", "onto-build"}, "rtk", "okf"); err != nil {
		t.Fatalf("Materialize: %v", err)
	}
	dispatcher := filepath.Join(dst, "onto", filepath.FromSlash(ToolingReferencePath))
	body, err := os.ReadFile(dispatcher)
	if err != nil {
		t.Fatalf("dispatcher sidecar missing: %v", err)
	}
	if !strings.Contains(string(body), "okf_lookup.py") {
		t.Errorf("sidecar does not reflect the declared providers:\n%s", body)
	}
	phase := filepath.Join(dst, "onto-build", filepath.FromSlash(ToolingReferencePath))
	if _, err := os.Stat(phase); !os.IsNotExist(err) {
		t.Errorf("non-dispatcher skill onto-build should not carry a sidecar (err=%v)", err)
	}
}

// Re-materializing with a different pair replaces the sidecar rather than
// leaving the previous providers in place.
func TestMaterialize_SidecarFollowsProviderChange(t *testing.T) {
	dst := t.TempDir()
	c := baseCatalog(t)
	if err := c.Materialize(dst, []string{"onto"}, "rtk", "graphify"); err != nil {
		t.Fatalf("Materialize: %v", err)
	}
	if err := c.Materialize(dst, []string{"onto"}, "none", "okf"); err != nil {
		t.Fatalf("re-Materialize: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dst, "onto", filepath.FromSlash(ToolingReferencePath)))
	if err != nil {
		t.Fatalf("sidecar missing after re-materialize: %v", err)
	}
	if strings.Contains(string(body), "graphify") {
		t.Errorf("stale provider survived re-materialize:\n%s", body)
	}
}

// An unknown provider is a programming error here (config validates first),
// so it must fail loudly rather than render an empty section.
func TestRenderTooling_RejectsUnknownProvider(t *testing.T) {
	if _, err := baseCatalog(t).RenderTooling("rtk", "ctags"); err == nil {
		t.Fatal("unknown code_intel provider should error")
	}
}

// The fingerprint changes with the pair and is stable for a fixed pair.
func TestToolingFingerprint_TracksThePair(t *testing.T) {
	c := baseCatalog(t)
	a, err := c.ToolingFingerprint("rtk", "graphify")
	if err != nil {
		t.Fatalf("ToolingFingerprint: %v", err)
	}
	same, err := c.ToolingFingerprint("rtk", "graphify")
	if err != nil {
		t.Fatalf("ToolingFingerprint: %v", err)
	}
	if a != same {
		t.Error("fingerprint is not stable for a fixed provider pair")
	}
	diff, err := c.ToolingFingerprint("rtk", "okf")
	if err != nil {
		t.Fatalf("ToolingFingerprint: %v", err)
	}
	if a == diff {
		t.Error("fingerprint must change when a provider changes")
	}
}
