package catalog

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/noviopenworks/homonto/internal/workspace"
)

const WorkspaceReferencePath = "references/workspace.md"

// HasWorkspaceReference limits layout instructions to shared workflow entry points.
func HasWorkspaceReference(name string) bool {
	return name == SharedKnowledgeSkill || name == "onto" || name == "to"
}

// RenderWorkspace describes only resolved configuration, never allocation or
// history state. Runtime inspect/list commands remain the authority for those.
func RenderWorkspace(l workspace.Layout) []byte {
	if !l.ExplicitRepos() {
		return nil
	}
	quote := func(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'" }
	var b bytes.Buffer
	b.WriteString("<!-- Generated by homonto apply. Do not edit. -->\n\n# Workspace layout\n\n")
	fmt.Fprintf(&b, "- Config schema: %d\n- Config file: `%s`\n- Config root: `%s`\n- Workflow root: `%s`\n- Workflow Git mode: `%s`\n", l.SchemaVersion, l.ConfigPath, l.ConfigRoot, l.WorkflowRoot, l.GitMode)
	if l.WorktreesDir == "" {
		b.WriteString("- WorktreesDir: not declared; do not allocate worktrees until worktrees.dir is explicitly configured.\n")
	} else {
		fmt.Fprintf(&b, "- WorktreesDir: `%s`\n", l.WorktreesDir)
	}
	b.WriteString("\n## Declared sources\n\nSchema 2 has no implicit config repository. Only these declared aliases are source repositories; the config root need not be Git.\n\n")
	names := make([]string, 0, len(l.Repos))
	for name := range l.Repos {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "- `%s`: `%s`\n", name, l.Repos[name])
	}
	if len(names) == 0 {
		b.WriteString("No source repositories declared. Do not infer one from the current directory.\n")
	}
	b.WriteString("\n## Runtime commands\n\nInspect current history and registered worktrees rather than treating this static reference as allocation state. Replace uppercase placeholders with the selected workflow, change, declared alias, explicit base ref, and new branch.\n\n```sh\n")
	fmt.Fprintf(&b, "homonto workspace inspect --config %s --json\n", quote(l.ConfigPath))
	fmt.Fprintf(&b, "homonto worktree list --config %s --json\n", quote(l.ConfigPath))
	fmt.Fprintf(&b, "homonto worktree create CHANGE --workflow onto --repo ALIAS --base BASE --branch BRANCH --config %s --json\n", quote(l.ConfigPath))
	fmt.Fprintf(&b, "homonto workspace checkpoint --config %s --message 'Describe the workflow edits' --path changes/CHANGE\n", quote(l.ConfigPath))
	b.WriteString("```\n\nUse `--workflow to` for a to task; checkpoint paths are workflow-root-relative (for example `tasks/TASK`), not source-root-relative.\n\n")
	if l.GitMode == "managed" {
		fmt.Fprintf(&b, "Managed mode owns a standalone records Git repository. Inspect first; explicit initialization, when authorized, is `homonto workspace init --config %s --yes`. Never initialize Git at the config root as a substitute.\n\n", quote(l.ConfigPath))
	} else {
		b.WriteString("Existing mode uses the workflow root's existing Git repository; it does not initialize or adopt a repository. The workspace checkpoint command above requires managed mode and is not available here; follow the existing repository's commit policy for workflow records.\n\n")
	}
	b.WriteString("## Working directories\n\nWorkflow commands use the config root, not the workflow root or a source checkout:\n\n```sh\n")
	fmt.Fprintf(&b, "onto status --dir %s\nto status --dir %s\n", quote(l.ConfigRoot), quote(l.ConfigRoot))
	b.WriteString("```\n\nonto/to currently load homonto.toml under `--dir`. If the actual config filename above differs, these commands do not select it: report that limitation rather than silently using a different config or creating homonto.toml.\n\nRun source Git, build, test, and edit operations in the selected source checkout or the exact registered worktree returned by create/list. Pass that working directory explicitly; never use the config root or workflow records root as a source fallback. Do not guess an allocation path from WorktreesDir.\n\nThe coordinator owns workflow records and checkpoints. Implementers receive declared source roots and only the explicitly trusted per-alias namespaces under WorktreesDir, not external workflow records. These path grants are not a shell sandbox. Read-only workers gain no shell or edit permission. The h entry points use this shared homonto reference and the onto/to dispatchers.\n")
	b.WriteString("\nNative edit denies cover workflow paths reported by the host's edit, write, and apply_patch permission requests. OpenCode v1.18.29 omits a move destination from apply_patch's edit-permission paths: an in-workspace move into records cannot be guaranteed blocked by these rules. Coordinator ownership remains binding even when the host omits a path; implementers must not edit or move files into workflow records. Routine scripts remain trusted execution, not a sandbox.\n")
	return b.Bytes()
}
